
name: codecov

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  pull_request:
    branches:
      - '*'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
          cache: 'pip'
      - run: python --version
      - run: pip install wheel
      - run: pip install -r coba/tests/requirements.txt
      - run: pip list
      - run: python setup.py install
      - run: coverage run -m unittest
      - run: coverage xml
      - uses: codecov/codecov-action@v2
