name: Linux / Python

on:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
        - { version: '3.6', experimental: false }
        - { version: '3.7', experimental: false }
        - { version: '3.8', experimental: false }
        - { version: '3.9', experimental: false }
        - { version: '3.10', experimental: true }
    continue-on-error: ${{ matrix.config.experimental }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.config.version }}
          cache: 'pip'
      - run: python --version
      - run: pip install wheel
      - run: pip install -r coba/tests/requirements.txt
      - run: pip list
      - run: python setup.py install
      - run: python -m unittest
