# codecov recommends calculating coverage on all configurations and submitting with flags
# here https://community.codecov.com/t/upload-of-coverage-of-several-python-versions/2349/2

#dependency caching does not appear to be working currently. All install steps take the same amount of time with and without dependency cahcing.

name: test doc and examples

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest took at least 20 minutes to complete so I've removed it for now
        # windows-latest took about 1:30 minutes longer than ubuntu so I've removed it for now
        os: [ubuntu-latest]
        python: ['3.8.x', '3.9.x', '3.10.x']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python --version
      - name: Install
        run: |
          pip install .[full]
          pip install -r coba/tests/requirements.txt
          pip list
      - name: Example Tests
        run: |
          python -c "from coba.environments import Environments; Environments.from_template('./examples/templates/feurer.json')"
          python -c "from coba.environments import Environments; Environments.from_template('./examples/templates/long.json')"
          python -c "from coba.environments import Environments; Environments.from_template('./examples/templates/short.json')"
          python "examples/scripts/Getting Started.py"
          python "examples/scripts/Custom Vowpal.py"
          python "examples/scripts/Logged Results.py"
      - name: Doc Tests
        run: |
          jupyter nbconvert --execute "doc/source/notebooks/Environments.ipynb" --inplace
          jupyter nbconvert --execute "doc/source/notebooks/Evaluators.ipynb" --inplace
          jupyter nbconvert --execute "doc/source/notebooks/Experiments.ipynb" --inplace
          jupyter nbconvert --execute "doc/source/notebooks/First_Experiment.ipynb" --inplace
          jupyter nbconvert --execute "doc/source/notebooks/Interactions.ipynb" --inplace
          jupyter nbconvert --execute "doc/source/notebooks/Learners.ipynb" --inplace
          jupyter nbconvert --execute "doc/source/notebooks/Results.ipynb" --inplace
