# codecov recommends calculating coverage on all configurations and submitting with flags
# here https://community.codecov.com/t/upload-of-coverage-of-several-python-versions/2349/2

name: unit_and_example_tests_with_code_coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-latest took at least 20 minutes to complete so I've removed it for now
        os: [windows-latest, ubuntu-latest]
        python: ['3.6.x', '3.7.x', '3.8.x', '3.9.x']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python --version
      #- run: pip install wheel
      - name: Min Dependency Unit Tests
      - run: python setup.py install -f
      - run: pip list
      - run: python -m unittest
      - name: Max Depdency Unit Tests with Coverage
      - run: pip install coverage
      - run: pip install -r coba/tests/soft_dependencies.txt
      - run: pip list
      - run: coverage run -m unittest
      - run: coverage xml
      - name: Report Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittest, ${{ matrix.os }}, ${{ matrix.version }}
      - name: Example Tests
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          pip install jupyterlab
          pip list
          python "examples/scripts/First Script.py"
          jupyter nbconvert --execute "examples/notebooks/First Experiment.ipynb" --inplace
          jupyter nbconvert --execute "examples/notebooks/Results.ipynb" --inplace
          jupyter nbconvert --execute "examples/notebooks/Experiments.ipynb" --inplace
          jupyter nbconvert --execute "examples/notebooks/Environments.ipynb" --inplace
